var test = require("node:test");
var assert = require("node:assert/strict");
var fs = require("node:fs");
var path = require("node:path");
var policy = require("../lib/session-title-policy");
var attachMessageProcessor = require("../lib/sdk-message-processor").attachMessageProcessor;

test("global-search titles use the visible query instead of provider boilerplate", function () {
  var transport = "This conversation began in Clay Studio's global search. Respond as Clay. User request: Find fruit";
  var apples = policy.selectInitialTitle({
    history: [{ type: "user_message", text: "Find my conversation about apple harvest planning" }],
  }, transport);
  var invoices = policy.selectInitialTitle({
    history: [{ type: "user_message", text: "Find the discussion about overdue client invoices" }],
  }, transport);

  assert.equal(apples.title, "Find my conversation about apple harvest planning");
  assert.equal(invoices.title, "Find the discussion about overdue client invoices");
  assert.notEqual(apples.title, invoices.title);
  assert.equal(apples.provisional, true);
});

test("provisional labels are distinct from fixed seeded titles", function () {
  assert.deepEqual(policy.selectInitialTitle({ title: "Nightly release" }, "ignored transport"), {
    title: "Nightly release",
    provisional: false,
  });
  assert.deepEqual(policy.selectInitialTitle({ history: [] }, "short"), {
    title: null,
    provisional: false,
  });
});

test("legacy global-search boilerplate titles repair from visible history", function () {
  var session = {
    title: "This conversation began in Clay Studio's global search. Resp",
    titleAutoGenerated: true,
    history: [{ type: "user_message", text: "Find the hiring plan from last month" }],
  };
  assert.equal(policy.repairLegacySearchTitle(session), true);
  assert.equal(session.title, "Find the hiring plan from last month");
  assert.equal(session.titleAutoGenerated, false);
  assert.equal(policy.repairLegacySearchTitle(session), false, "repair runs only once");
});

test("Home titles become semantic after the first completed exchange", function () {
  assert.equal(policy.generationTurn(true), 1);
  assert.equal(policy.generationTurn(false), 2);
});

function titleProcessor(isMate, onAutoTitle) {
  return attachMessageProcessor({
    sm: {
      sendAndRecord: function () {},
      sendToSession: function () {},
      broadcastSessionList: function () {},
    },
    send: function () {},
    slug: isMate ? "mate-clay" : "project",
    isMate: isMate,
    mateDisplayName: isMate ? "Clay" : "",
    getNotificationsModule: function () { return null; },
    shouldSuppressResponseNotification: function () { return true; },
    onProcessingChanged: function () {},
    onAutoTitle: onAutoTitle,
  });
}

function completedSession() {
  return {
    localId: 1,
    history: [{ type: "user_message", text: "Plan the launch campaign" }],
    blocks: {},
    sentToolResults: {},
    pendingPermissions: {},
    pendingElicitations: {},
    pendingAskUser: {},
    activeTaskToolIds: {},
    taskIdMap: {},
    responsePreview: "Here is a plan.",
    isProcessing: true,
    titleAutoGenerated: false,
    titleManuallySet: false,
    turnCount: 0,
  };
}

test("completed Home turns request a semantic title immediately", function () {
  var calls = 0;
  var processor = titleProcessor(true, function () { calls++; });
  processor.processSDKMessage(completedSession(), { yokeType: "result", cost: 1, duration: 1 });
  assert.equal(calls, 1);
});

test("ordinary project sessions retain the two-turn title threshold", function () {
  var calls = 0;
  var processor = titleProcessor(false, function () { calls++; });
  var session = completedSession();
  processor.processSDKMessage(session, { yokeType: "result", cost: 1, duration: 1 });
  assert.equal(calls, 0);
  session.isProcessing = true;
  session.responsePreview = "More detail.";
  processor.processSDKMessage(session, { yokeType: "result", cost: 1, duration: 1 });
  assert.equal(calls, 1);
});

test("query startup adopts provisional titles without marking them generated", function () {
  var bridge = fs.readFileSync(path.join(__dirname, "..", "lib", "sdk-bridge.js"), "utf8");
  assert.match(bridge, /sessionTitlePolicy\.selectInitialTitle\(session, text\)/);
  assert.match(bridge, /session\.titleAutoGenerated = !initialTitleProvisional/);
});
